### ISSUE TITLE
Please, add license file or mention license in readme

### ISSUE THREAD

**Issue by matkoniecz** [mhl/github-issues-scripts#1]
Currently no license is mentioned anywhere, what makes this script fully copyrighted. It strongly limits usefulness of open-sourcing it.

Can you consider licensing this program using one of [standard licenses](http://opensource.org/licenses)?

In case that for some reason not releasing it under open license is intentional - mentioning it in readme also would be a good idea.

**Comment by matkoniecz** [comment]
@mhl Is there any chance of making this code really usable by licensing it?

**Comment by mhl** [comment]
@matkoniecz I've done that now (GNU GPL v3). Apologies for the delay - I have a few associated scripts (for dealing with estimation) that I was meaning to tidy up and include as well at the same time, but didn't have time for that bit; I should have just included the license without waiting for that, as I've done now.

**Comment by matkoniecz** [comment]
Thanks!
